# Generated by Django 5.2 on 2025-04-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='address',
            new_name='publisher',
        ),
    ]
